### ISSUE TITLE
Error on adding virustotal api key

### ISSUE THREAD

**Issue by ShinTakata** [CYB3RMX/Qu1cksc0pe#13]
How to add virustotal api key? because when i add one using --key_init argument  

qu1cksc0pe --key_init <Virustotal Api Key>

qu1cksc0pe: error: unrecognized arguments: <virustotal api key>

it says qu1cksc0pe: error: unrecognized arguments

**Comment by CYB3RMX** [comment]
Hello,
Did you try to run this command?
```python3 qu1cksc0pe.py --key_init```

**Comment by ShinTakata** [comment]
yes and this error code appear qu1cksc0pe: error: unrecognized arguments:

**Comment by CYB3RMX** [comment]
What distro are you currently using? and did you installed program on your system?

**Comment by ShinTakata** [comment]
I'm using vps server running ubuntu 20.04

**Comment by CYB3RMX** [comment]
Hello again. I did some checked program again and everything seems okay.
**(Note: I didn't install program on my system)**

![forgit](https://user-images.githubusercontent.com/42123683/150231967-ed678096-6c2f-46de-9650-27b1efbd1232.png)
