### ISSUE TITLE
qu1ckSc0pe's nonExecAnalyzer module fails VBA Macro retrieval

### ISSUE THREAD

**Issue by patriciamespert** [CYB3RMX/Qu1cksc0pe#15]
When executing qu1cksc0pe in order to analyze document files (--doc argument) qu1cksc0pe's nonExecAnalyzer module is used to initiate VBA Macro retrieval.  

Problem gets here
https://github.com/CYB3RMX/Qu1cksc0pe/blob/6ca111c5df3e1f4873e5fd26bb1b5ec911e8365e/Modules/nonExecAnalyzer.py#L50

Once olevba tool gets instantiated as vbaparser a non existing property (contains_macros) gets called causing an Exception therefore get this error "An error occured while parsing that file for macro scan"
Solution seems to replace contains_macro by contains_vba_macros.

This is the final output (once the problem is solved)
![issue](https://user-images.githubusercontent.com/45337012/161088991-90a6c926-629b-44bb-a83e-485bd1bde12a.png)

**Comment by CYB3RMX** [comment]
Hello. Thank you for suggestions! It will be fixed A.S.A.P.
