### ISSUE TITLE
linux usage

### ISSUE THREAD

**Issue by mispuser21** [CYB3RMX/Qu1cksc0pe#17]
how do i use qu1cksc0pe to  analyze linux binaries dynamically?

**Comment by CYB3RMX** [comment]
You can use  ```--watch``` argument.
For example: ```python3 qu1cksc0pe.py --file linux_binary --watch```

**Comment by mispuser21** [comment]
what about the emulator part? do i need to link a vm?

**Comment by CYB3RMX** [comment]
No you dont need a VM. Emulator is Qiling based so when you execute the ```--watch``` argument Qu1cksc0pe downloads the rootfs for target binary and tries to execute that binary in downloaded rootfs

**Comment by mispuser21** [comment]
thank you

**Comment by mispuser21** [comment]
hi, i just tried to execute the watch command but i currently face this error...
![Screenshot from 2022-10-12 09-04-12](https://user-images.githubusercontent.com/113578411/195225476-e7952239-2540-49ce-8157-e123fbef9024.png)
 how do i get around it?

**Comment by CYB3RMX** [comment]
Hmm i think that error related to Qiling. Sometimes I encounter this errors to. I will look for it
