### ISSUE TITLE
requirements.txt gives an error

### ISSUE THREAD

**Issue by kidvidearths** [CYB3RMX/Qu1cksc0pe#23]
When i try to run bash setup.py on my virtual environment, i get this error.
Could not find a version that satisfies the requirement yara-python-dex>=1.0.1 (from apkid->-r requirements.txt (line 3)) (from versions: none)

**Comment by CYB3RMX** [comment]
This error is common in apkid. I encountered this error while I was trying to use Qu1cksc0pe in Kali and KaliWSL. Can you try these following commands:
1. Uninstall existing yara module: ```pip3 uninstall yara-python```
2. Install version 3.11.0: ```pip3 install yara-python==3.11.0```
3. Try to run program again

I think these instructions will fix your problem.

**Comment by kidvidearths** [comment]
I get a new error now.
Building wheel for keystone-engine (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zc_qayn_/keystone-engine/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zc_qayn_/keystone-engine/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vbi0l2_n
       cwd: /tmp/pip-install-zc_qayn_/keystone-engine/
  Complete output (6 lines):
  running bdist_wheel
  running build
  Building C++ extensions
  ../make-share.sh: 21: cmake: not found
  make: *** No targets specified and no makefile found.  Stop.
  error: [Errno 2] No such file or directory: '/tmp/pip-install-zc_qayn_/keystone-engine/src/build/llvm/lib64/libkeystone.so'
  ----------------------------------------
  ERROR: Failed building wheel for keystone-engine

**Comment by kidvidearths** [comment]
Am i supposed to run this in a virtual environment?

**Comment by kidvidearths** [comment]
I'm running this in a virtual environment and i tried doing what you asked, it didn't work. Even went to change it in requirements.txt. Anyways, the error goes when i change the apkid version in line 3 to ==2.1.1 and run bash setup.sh, but it's introducing new errors. I'm using an ubuntu btw
<img width="808" alt="Screenshot 2023-03-29 at 1 11 54 PM" src="https://user-images.githubusercontent.com/108454526/228461883-50b2da70-99e0-42b1-b087-3e847e4c1abc.png">

**Comment by CYB3RMX** [comment]
Looks like you dont have ```cmake```. Try to install it via your package manager. I added virtual environment because of module conflict errors. I will make it optional with new update. Honestly I didnt ever used Qu1cksc0pe on the Ubuntu. For best experience you can use it on Parrot or Kali. I will try it on Ubuntu and add optimizations for this.

**Comment by kidvidearths** [comment]
Okay, when i try to install it, it gives me this error. I've moved onto kali as you'd suggested.
<img width="588" alt="Screenshot 2023-03-29 at 6 09 11 PM" src="https://user-images.githubusercontent.com/108454526/228537758-ee64416e-a279-46b8-81cc-6abb912d8b1e.png">

**Comment by CYB3RMX** [comment]
Looks like when you want to install it from virtual environment it crashes. But dont worry I'll make virtual environment usage is optional very soon.

**Comment by CYB3RMX** [comment]
Can you update the program and retry please?
