### ISSUE TITLE
Is it possible to conduct malware analysis for file size greater then 4 GB using Qu1cksc0pe?

### ISSUE THREAD

**Issue by sahil3112** [CYB3RMX/Qu1cksc0pe#25]

**Comment by CYB3RMX** [comment]
Hello sir. Thank you for your question. Qu1cksc0pe is not able to analyze large files for now. But I will add ```pumped-file``` analysis techniques very soon. So anyone can analyze and extract actual malwares from large files.

**Comment by CYB3RMX** [comment]
Hello again! I added large file analysis techniques to project. You can now check this out!
