### ISSUE TITLE
Distutils package is deprecated

### ISSUE THREAD

**Issue by MulletGoneViral** [CYB3RMX/Qu1cksc0pe#26]
I ran setup.sh in WSL in windows 11 and got this error:

/home/mulletgoneviral/Downloads/opt/pyexiftool/setup.py:17: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup
Traceback (most recent call last):
  File "/home/mulletgoneviral/Downloads/opt/pyexiftool/setup.py", line 17, in <module>
    from distutils.core import setup

I also get this error:

cp: cannot stat 'Modules/lib/sc0pe_helper.py': No such file or directory

I checked the setup.sh file and cannot see where sc0pe_helper.py gets installed, is this error related to the previous one?

**Comment by CYB3RMX** [comment]
Hello there! Looks like the ```distutils``` error is related to ```pyexiftool``` repository. I will try to test setup.sh on my WSL and check what is wrong. Can you clone Qu1cksc0pe again and re-execute setup.sh script then send me screenshots about errors?

Note: Make sure if ```sc0pe_helper.py``` file contained in the new cloned repository directories

**Comment by MulletGoneViral** [comment]
I found the problem for the second error. Turns out the git clone command didn't complete properly and some files like sc0pe_helper.py where not downloaded. I ran setup.sh but it still did not work and I got this error:
<img width="936" alt="image" src="https://github.com/CYB3RMX/Qu1cksc0pe/assets/123521207/b88a57d0-7b66-4b69-be38-b47a3cfd9b3a">

I am using python 3.11.2.

**Comment by CYB3RMX** [comment]
Hmm according to that error messages Can you do these things?:
1. ```setup.sh: line 17: pip3 command not found``` => Make sure you have the pip3 command. To install pip3 you can execute: ```sudo apt install python3-pip```
2. Looks like you couldn't install the ```exiftool``` binary via ```apt```. You got unmet dependency errors.

If you fix that these problems and then restart the ```setup.sh``` script It should work properly.

Thank you for your report. I'll add pip3 existence check to ```setup.sh``` script.

**Comment by MulletGoneViral** [comment]
Thank you for the help and fast response, every thing seems to be installed properly but now I'm getting puremagic errors: 
<img width="387" alt="image" src="https://github.com/CYB3RMX/Qu1cksc0pe/assets/123521207/453a6847-7db7-4314-8298-d8f3d770ed0f">

**Comment by CYB3RMX** [comment]
Thank you for your comments. I hope it was useful for you :)
