### ISSUE TITLE
Error: >pythonnet< module not found.

### ISSUE THREAD

**Issue by KDPryor** [CYB3RMX/Qu1cksc0pe#28]
I installed the latest version of Qu1cksc0pe this evening. Previous versions worked fine, but when I tried to analyze a Windows PE32 file I got "Error: >pythonnet< module not found."
I have run the setup.sh script and no errors were noted during the setup.

**Comment by CYB3RMX** [comment]
Hello! This error occured because of the new update. Can you execute this following command? So your problem will be solved
```pip3 install pythonnet```

**Comment by tuttimann** [comment]
I have the same issue, also installing pythonnet via pip3 didn't solve it.

**Comment by CYB3RMX** [comment]
Can you send me a screenshot of errors?

**Comment by tuttimann** [comment]
I have attached a screenshot. I tried it on Kali and Ubuntu, both on WSL2.
![qu1cks0pe](https://github.com/CYB3RMX/Qu1cksc0pe/assets/35948670/6452a996-b11a-483f-8b62-0803f3c03f11)

**Comment by lolmarc** [comment]
Same as me.
![image](https://github.com/CYB3RMX/Qu1cksc0pe/assets/99796146/1baab15e-ee99-48a7-b1b1-2708edbe1063)

**Comment by CYB3RMX** [comment]
Okay it seems you need to install Mono on your system. 
Solution: ```sudo apt install mono-complete``` will fix your problem

After installing mono Qu1cksc0pe will be work properly

**Comment by lolmarc** [comment]
Thanks a lot, with the solution it works.

**Comment by CYB3RMX** [comment]
You're welcome :)
