### ISSUE TITLE
Error Puremagic not found

### ISSUE THREAD

**Issue by hack-parthsharma** [CYB3RMX/Qu1cksc0pe#29]
![image](https://github.com/CYB3RMX/Qu1cksc0pe/assets/69046031/6a919711-9da0-4fd4-bf1f-aedbfdf05c40)

I have installed the package manually still same error is showing

![image](https://github.com/CYB3RMX/Qu1cksc0pe/assets/69046031/9f912451-56d4-4c35-919f-cd28b7d49828)

@CYB3RMX

**Comment by CYB3RMX** [comment]
Hello! Did you execute this command?: ```sudo pip3 install -r requirements.txt```

**Comment by hack-parthsharma** [comment]
@CYB3RMX How can i add that path "/home/kali/.local/bin" ?

**Comment by hack-parthsharma** [comment]
Also if possible can you give some repositories in which i can find the virus and malware for testing purpose ! Thanks once again for creating such an amazing tool !

**Comment by CYB3RMX** [comment]
To add "/home/kali/.local/bin" to the PATH environment variable in Kali Linux, you can follow these steps:

1. Open a terminal in Kali Linux. You can do this by clicking on the terminal icon in the taskbar or by pressing Ctrl+Alt+T.

2. Once the terminal is open, you need to locate and open the file where the PATH variable is defined. In Kali Linux, the file is usually either `~/.bashrc` or `~/.bash_profile`.

   Type the following command to open the file in a text editor:

   ```bash
   nano ~/.bashrc
   ```

   If the file doesn't exist, you can create it by running the command:

   ```bash
   touch ~/.bashrc
   nano ~/.bashrc
   ```

3. In the text editor, scroll to the bottom of the file and add the following line:

   ```bash
   export PATH="/home/kali/.local/bin:$PATH"
   ```

   This line appends "/home/kali/.local/bin" to the existing PATH variable, separated by a colon.

4. Save the changes by pressing Ctrl+O, then press Enter to confirm the filename. Exit the text editor by pressing Ctrl+X.

5. To apply the changes to the current terminal session, run the following command:

   ```bash
   source ~/.bashrc
   ```

   Alternatively, you can close the terminal and open a new one to automatically load the updated PATH variable.

Now, when you run commands in the terminal, it will check the "/home/kali/.local/bin" directory for executable files as part of the PATH search.

**Comment by CYB3RMX** [comment]
Also you can find malware samples from:
1. Malware Bazaar: https://bazaar.abuse.ch/browse/
2. theZoo: https://github.com/ytisf/theZoo
3. VirusShare: https://virusshare.com/
4. VX-Underground: https://www.vx-underground.org/malware.html

So actually there is many of them. You can also simply google it and find another ones too.

Thank you for your comments. I hope it will be usefull :)

**Comment by hack-parthsharma** [comment]
Thanks a lot dude for the immediate help. Really appreciate your efforts and help.
