### ISSUE TITLE
puremagic not found error when installing

### ISSUE THREAD

**Issue by greaterthanstar** [CYB3RMX/Qu1cksc0pe#3]
`mr@box:~/repos/Qu1cksc0pe$ pip3 install puremagic`
Requirement already satisfied: puremagic in /home/mr/.local/lib/python3.8/site-packages (1.11)
`mr@box:~/repos/Qu1cksc0pe$ sudo python3 qu1cksc0pe.py --install`
Error: >puremagic< module not found.

I ran the requirements installer and it was successful. And I tried installing it manually as shown above. I don't know all that much about python, but the qu1cksc0pe.py file looks like it's just trying to do a simple `import puremagic` so I don't know why it isn't finding it. This is on WSL Ubuntu.

I can run quickscope manually without installing just fine.

**Comment by CYB3RMX** [comment]
You installed ```puremagic``` as normal user but you executed program as sudo. When you execute any program as sudo python looks modules for root user. You can try execute qu1cksc0pe without sudo then it should work correctly. I will try install Qu1cksc0pe on ubuntu distro either.
