### ISSUE TITLE
sc0pe_helper library not installed

### ISSUE THREAD

**Issue by musman12362** [CYB3RMX/Qu1cksc0pe#30]
hey can anyone help me out in this ?
i run the command **bash setup.sh** but its not installing **sc0pe_helper** module .due to which I'm unable to excute **quicksc0pe.py**
i also tried to install this as a separate python package but i did not fine any python package named as scope_helper.

how i can resolve this issue? 

![Screenshot from 2023-06-26 12-33-28](https://github.com/CYB3RMX/Qu1cksc0pe/assets/113498180/dff8c64d-18bb-4bad-9e8b-53767a4ecce8)

**Comment by CYB3RMX** [comment]
Hey there! Looks like you need to install ```git``` command first. Can you execute this command: ```sudo apt install git```. After installing git command re-execute the ```setup.sh``` it should work properly.

**Comment by musman12362** [comment]
> Hey there! Looks like you need to install `git` command first. Can you execute this command: `sudo apt install git`. After installing git command re-execute the `setup.sh` it should work properly.

thank you for your response. I'll try this

**Comment by CYB3RMX** [comment]
Hmm I see. But where is the Qu1cksc0pe directory?. Because the setup script looks for ```Modules``` directory which has been contained on Qu1cksc0pe directory. Can you execute this commands:
- ```cd Qu1cksc0pe```
- ```bash setup.sh```

**Comment by musman12362** [comment]
> Hmm I see. But where is the Qu1cksc0pe directory? Because the setup script looks for `Modules` directory which has been contained on `Qu1cksc0pe` directory. Can you execute this commands:
> 
>     * `cd Qu1cksc0pe`
> 
>     * `bash setup.sh`

Thank you I installed it

**Comment by CYB3RMX** [comment]
You're welcome :)
