### ISSUE TITLE
while running a bit large file of 61 mb

### ISSUE THREAD

**Issue by Yashsomalkar** [CYB3RMX/Qu1cksc0pe#34]
processing buffer... ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  13% -:--:--
Traceback (most recent call last):
  File "/home/yash/Downloads/Qu1cksc0pe/Modules/sigChecker.py", line 217, in <module>
    sig_check = SignatureChecker(target_file=sys.argv[1])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yash/Downloads/Qu1cksc0pe/Modules/sigChecker.py", line 58, in __init__
    self.pumped_file_carver()
  File "/home/yash/Downloads/Qu1cksc0pe/Modules/sigChecker.py", line 174, in pumped_file_carver
    exec_size = self.parse_pe_size(buffer_read)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yash/Downloads/Qu1cksc0pe/Modules/sigChecker.py", line 205, in parse_pe_size
    size_of_image = struct.unpack('<L', pe_data[size_of_image_offset:size_of_image_offset + 4])[0]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by CYB3RMX** [comment]
Hello @Yashsomalkar!

Can you send me the full output of the error message or screenshot?

**Comment by Yashsomalkar** [comment]
Sure i will send it by tomorrow

**Comment by AyushSahu77** [comment]
Is this fixed? I am still having trouble when scanning an exe file.

**Comment by CYB3RMX** [comment]
Hello again @AyushSahu77 !

Can you send me the hash value of the file? So I can check that to

**Comment by AyushSahu77** [comment]
Yes surely, here are the md5 and shasum for the file:

**md5**: 4608ebf38bdb5e667d53275de4ccfe11
**sha256**: 0657caaf0fbfa1f8e2c3bb73bc34cd1a0e0c61feb0f5440becec57ffc5e31a28

Pinning direct link to the  file as well: https://www.hidglobal.com/sites/default/files/drivers/Asure_ID_Setup_v7.8.6.537.exe
