### ISSUE TITLE
Can't build Docker image

### ISSUE THREAD

**Issue by netoeuler** [CYB3RMX/Qu1cksc0pe#37]
On "Setup and Installation" section, it says that to use the Docker image, have to run the command:
`docker build qu1cksc0pe .`

But it returns the following:
> ERROR: "docker buildx build" requires exactly 1 argument.
> See 'docker buildx build --help'.
> 
> Usage:  docker buildx build [OPTIONS] PATH | URL | -
> 
> Start a build

So, I had to run the command:
`docker build .`

Which returned the following:
> [+] Building 1.4s (12/15)                                                                                docker:default
>  => [internal] load .dockerignore                                                                                  0.0s
>  => => transferring context: 2B                                                                                    0.0s
>  => [internal] load build definition from Dockerfile                                                               0.0s
>  => => transferring dockerfile: 713B                                                                               0.0s
>  => [internal] load metadata for docker.io/library/ubuntu:latest                                                   0.8s
>  => [ 1/11] FROM docker.io/library/ubuntu:latest@sha256:2b7412e6465c3c7fc5bb21d3e6f1917c167358449fecac8176c6e496e  0.0s
>  => [internal] load build context                                                                                  0.1s
>  => => transferring context: 20.08kB                                                                               0.0s
>  => CACHED [ 2/11] RUN apt update && apt install -y curl wget git binutils sudo unzip python3 python3-pip mono-co  0.0s
>  => CACHED [ 3/11] RUN pip3 install setuptools wheel pythonnet pycryptodome python-magic                           0.0s
>  => CACHED [ 4/11] WORKDIR /app                                                                                    0.0s
>  => CACHED [ 5/11] COPY . .                                                                                        0.0s
>  => CACHED [ 6/11] RUN chmod +x qu1cksc0pe.py setup.sh                                                             0.0s
>  => CACHED [ 7/11] RUN ln -s /root /home/root                                                                      0.0s
>  => ERROR [ 8/11] RUN ./setup.sh                                                                                   0.5s
> \-\-----
>  \> [ 8/11] RUN ./setup.sh:
> 0.428 /bin/sh: 1: ./setup.sh: not found
> \-\-----
> Dockerfile:17
> \-\-------------------
>   15 \|     RUN chmod +x qu1cksc0pe.py setup.sh
>   16 \|     RUN ln -s /root /home/root
>   17 \| >>> RUN ./setup.sh
>   18 \|     RUN wget https://raw.githubusercontent.com/CYB3RMX/MalwareHashDB/main/HashDB -O /home/root/sc0pe_Base/HashDB
>   19 |
> \-\-------------------
> ERROR: failed to solve: process "/bin/sh -c ./setup.sh" did not complete successfully: exit code: 127

These steps were done on Windows 10 with Docker v4.24.0

**Comment by CYB3RMX** [comment]
Hey there!
Thank you for your report! I will fix that issue ASAP!

**Comment by CYB3RMX** [comment]
Hello again!

I tested this case on my own system and everything seems to be OK. 

Can you make sure that you are building the docker image on the correct directory with this following command:

`docker build -t qu1cksc0pe .`

**Comment by netoeuler** [comment]
Sorry for the late reply.
I'm running the command `docker build -t qu1cksc0pe .` from the Qu1cksc0pe directory and now it works, but I'm still getting the following error:

=> [ 6/10] RUN ln -s /root /home/root                                                                             0.3s
=> ERROR [ 7/10] RUN ./setup.sh                                                                                   0.5s
\------
 > [ 7/10] RUN ./setup.sh:
0.444 /bin/sh: 1: ./setup.sh: not found
\------
Dockerfile:18
\--------------------
  16 |     #RUN chmod +x qu1cksc0pe.py setup.sh
  17 |     RUN ln -s /root /home/root
  18 | >>> RUN ./setup.sh
  19 |     RUN wget https://github.com/CYB3RMX/MalwareHashDB/raw/main/HashDB -O /home/root/sc0pe_Base/HashDB
\--------------------
ERROR: failed to solve: process "/bin/sh -c ./setup.sh" did not complete successfully: exit code: 127
