### ISSUE TITLE
Error: >rich< module not found.

### ISSUE THREAD

**Issue by Th3Heavy** [CYB3RMX/Qu1cksc0pe#39]
hello, i get an error when i want to use.

my command to install:
git clone https://github.com/CYB3RMX/Qu1cksc0pe.git
bash setup.sh
sudo python qu1cksc0pe.py --install

error:
Error: >rich< module not found.

Requirement already satisfied: rich in /home/ben/.local/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (13.7.0)

ben@BEN:~/Qu1cksc0pe$ python --version
Python 3.11.1

Linux BEN 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linu
DEBIAN 11.6

**Comment by CYB3RMX** [comment]
No problem. You can also use Qu1cksc0pe from docker.
