### ISSUE TITLE
doc scanning didn't work without bs4

### ISSUE THREAD

**Issue by cjastacio** [CYB3RMX/Qu1cksc0pe#40]
Not sure how much of an issue this is but I was working on a file after building the docker image and found that adding bs4 to requirements.txt got the analysis done. 

`docker run -it --rm -v $(pwd):/data qu1cksc0pe:latest --file /data/suspect.docx --docs
`
Granted, I'm aware that this is an unsupported file but my qu1cksc0pe image was running fine but spit out. 

```
raceback (most recent call last):
  File "/app/Modules/document_analyzer.py", line 14, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
```

So I removed the already built docker, added bs4 to requirements.txt, and rebuilt and all was fine again. 

Not sure if there are other requirements missing?

**Comment by CYB3RMX** [comment]
Hello @cjastacio !

Thank you for your report. This issue will be fixed very soon!

Have a nice day.
