### ISSUE TITLE
New install doesn't work -- /usr/bin/qu1cksc0pe: cannot execute: required file not found

### ISSUE THREAD

**Issue by KDPryor** [CYB3RMX/Qu1cksc0pe#41]
Hello,

I updated Qu1cksc0pe today after quite some time on an older version. I downloaded the latest, ran setup.sh and then sudo python3 qu1cksc0pe.py --install. The install seems to go well but when trying to run qu1cksc0pe I get the following output:

bash: /usr/bin/qu1cksc0pe: cannot execute: required file not found

I have tried uninstalling and reinstalling without success. If I just run python ./qu1cksc0pe.py it seems work normally, but the installed version will not work. I'm unsure how to troubleshoot this further.

**Comment by KDPryor** [comment]
Also, when installing I had issues with the shebang being /usr/bin/env python3 and had to change it to /usr/bin/python3 to make it work at all.

**Comment by CYB3RMX** [comment]
Hello @KDPryor !

Thank you for your report. I will fix the installation issues in the next update ASAP!

If you find another issues feel free to share with me.

**Comment by KDPryor** [comment]
Thank you very much! Also, just for your info, I failed to mention that I'm using Debian 12.
