### ISSUE TITLE
please support installation arch linux x86_64

### ISSUE THREAD

**Issue by 3xploiton3** [CYB3RMX/Qu1cksc0pe#42]
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.

    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.

    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by CYB3RMX** [comment]
Hello @3xploiton3 !

Thank you for your report. Which arch-based distro did you use?

**Comment by 3xploiton3** [comment]
I'm just use arch, not distro

![image](https://github.com/CYB3RMX/Qu1cksc0pe/assets/19517680/0a260786-2435-4f59-ac19-6e740b8d859c)
