### ISSUE TITLE
Report flag not working when analyzing exe files.

### ISSUE THREAD

**Issue by SalehHub** [CYB3RMX/Qu1cksc0pe#46]
**Issue Title:** Report flag has no effect

**Description:**
The report flag seems to have no effect when attempting to export a JSON report using the following command:

```bash
python qu1cksc0pe.py --file exefile --analyze --report
```

**Steps to Reproduce:**
1. Run the specified command with the --file and --report flags.

**Expected Behavior:**
A JSON report should be generated as expected.

**Actual Behavior:**
No report is generated, indicating that the report flag has no effect.

I have solved the issue by commenting out line 131 in winAnalyzer.py.

**Comment by CYB3RMX** [comment]
Hello @SalehHub !

Thank you for your report. However the proper usage of the ```--report``` flag is:

```python3 qu1cksc0pe.py --file your_exe_file --analyze --report```

Note: If you still have errors on this usage feel free to share with me.

**Comment by SalehHub** [comment]
> Hello @SalehHub !
> 
> 
> 
> Thank you for your report. However the proper usage of the ```--report``` flag is:
> 
> 
> 
> ```python3 qu1cksc0pe.py --file your_exe_file --analyze --report```
> 
> 
> 
> Note: If you still have errors on this usage feel free to share with me.

Thanks for quick reply. Yes that how I used it, the issue still exists.

**Comment by CYB3RMX** [comment]
Can you share the target sample hash/link etc. with me for fixing this issue?

**Comment by SalehHub** [comment]
05072a7ec455fdf0977f69d49dcaaf012c403c9d39861fa2216eae19c160527f.7z

Extracted. 

You can download it form using this link

https://vx-underground.org/Samples/Families/AESRTRansomware

**Comment by CYB3RMX** [comment]
Hello again @SalehHub !

Thank you for your report. I have made some improvements to the project in response to this issue. Now you can properly analyze your sample :)
