### ISSUE TITLE
exec /app/qu1cksc0pe.py: no such file or directory

### ISSUE THREAD

**Issue by cayubweeums** [CYB3RMX/Qu1cksc0pe#53]
Hey Team!!

I am trying to utilize this project and am struggling with implementing the docker version of this tool in my lab. I am unsure what I am doing wrong here, but clearly docker cannot see where I have pulled the code base to. I have listed below what I believe is relevant. Please ask if you need any more info! 

As an aside, I love this tool. Great work is being done here!!!

Steps to reproduce:
- Fresh Ubuntu LTS VM built and configured for docker containers
- `git clone https://github.com/CYB3RMX/Qu1cksc0pe.git`
- `cd Qu1cksc0pe`
- `sudo docker build -t qu1cksc0pe .`
- `sudo docker run -it --rm -v $(pwd):/data qu1cksc0pe:latest --file /data/requirements.txt --docs`

Error Log:
```
~/Qu1cksc0pe$ sudo docker run -it --rm -v $(pwd):/data qu1cksc0pe:latest --file /data/requirements.txt --docs
exec /app/qu1cksc0pe.py: no such file or directory
```

The analysis on the code base's own `requirement.txt` may not work, but I am unable to even get to the point where the container would throw that error. It will not even run to begin with. I have made it function with only the python install, but my lab would benefit from this being something that I could containerize. Thanks for your help in advance!!!

**Comment by cayubweeums** [comment]
Looks like this is an issue with the `ENTRYPOINT` in the [Dockefile](https://github.com/CYB3RMX/Qu1cksc0pe/blob/master/Dockerfile). The 'executable' portion of the `ENTRYPOINT` should be `python3` with the 'parameter' portion being the `/app/qu1cksc0pe.py`.

So if we can change [this line](https://github.com/CYB3RMX/Qu1cksc0pe/blob/8891615416aefeff45f4cdcb9270f4ee4f72b1ca/Dockerfile#L25C1-L25C34) to `ENTRYPOINT ["python3", "/app/qu1cksc0pe.py"]` my issue would be resolved!

I don't have perms to make a PR or else I would've made the changes myself.

**Comment by CYB3RMX** [comment]
Hello @cayubweeums !

Thank you for your nice comments and report! I will fix that issue as soon as possible.

**Comment by CYB3RMX** [comment]
No problem. You are very welcomed to contribute :)
