### ISSUE TITLE
Report flag not working when analyzing exe files

### ISSUE THREAD

**Issue by dfirale** [CYB3RMX/Qu1cksc0pe#71]
The same issue described here still exists #46 

Please note that the author of the earlier issue mentioned commenting out line number 131 after which the report function started working. However, the winAnalyzer.py (windows_static_analyzer.py) code has since changed, and I was unable to implement a similar fix.

It also seems that adding a print statement at the end of the code does not produce any output, even when the --report flag is issued: https://github.com/CYB3RMX/Qu1cksc0pe/blob/master/Modules/windows_static_analyzer.py#L685

**Description**:
The report flag seems to have no effect when attempting to export a JSON report using the following command:

`python qu1cksc0pe.py --file exefile --analyze --report`

Exe file used: https://bazaar.abuse.ch/sample/5ffb7e55dfcaa0e7c0cdff4ac800c19ebfdcbd44f54caab489d53ecb3c55c5d3/

**Steps to Reproduce**:

Run the specified command with the --file and --report flags.

**Expected Behavior**:
A JSON report should be generated as expected.

**Actual Behavior**:
No report is generated, indicating that the report flag has no effect.

**Comment by CYB3RMX** [comment]
Hello @dfirale ! Thank you for your report. I' ll fix that issue as soon as possible 👍

**Comment by dfirale** [comment]
Thanks for pointing that out! The report function indeed works on other samples.
